[hooks]
postinstall = 'npx corepack enable'

[tasks]
"prettier:fix" = "pnpm run prettier:fix"
"lint:fix" = "pnpm run lint:fix"
build = "pnpm run -r build"
clean = "pnpm run -r clean"
test = "pnpm run -r test"

[tasks.pre-commit]
depends = ["prettier:fix", "lint:fix", "build"]

[alias]
pnpm = "asdf:https://github.com/jonathanmorley/asdf-pnpm.git"
