import { GroupSettings } from "./directory.js";

/**
 * The four named Groups Settings templates staff choose from in the CRM, mirroring
 * `gam/templates/*.json` - the break-glass GAM path's copy of these same settings. Keep the two in
 * step; see `gam/README.md`.
 *
 * `allowExternalMembers: "true"` is load-bearing on `participants`: guardians are on personal
 * Gmail, and without it they can be added to a group but receive nothing. A class group (members
 * discuss among themselves) takes `participants`; a program group (a broadcast surface over its
 * class sub-groups) takes `announcement`.
 *
 * Groups Settings fields are strings even where they read as booleans or enums - the API rejects
 * real JSON booleans on several fields, so `"true"` and `"false"` here are deliberate, not typos.
 * One field is `default_sender`, not `defaultSender` like the rest - `googleapis`'s generated
 * `Schema$Groups` type names it that way, unlike the GAM files' camelCase copy.
 */
const announcement: GroupSettings = {
  allowExternalMembers: "true",
  allowWebPosting: "true",
  archiveOnly: "false",
  customFooterText: "",
  customRolesEnabledForSettingsToBeMerged: "false",
  defaultMessageDenyNotificationText: "",
  default_sender: "DEFAULT_SELF",
  enableCollaborativeInbox: "false",
  includeCustomFooter: "false",
  includeInGlobalAddressList: "true",
  isArchived: "true",
  maxMessageBytes: 26214400,
  membersCanPostAsTheGroup: "false",
  messageModerationLevel: "MODERATE_NONE",
  replyTo: "REPLY_TO_IGNORE",
  sendMessageDenyNotification: "true",
  showInGroupDirectory: "false",
  spamModerationLevel: "MODERATE",
  whoCanAdd: "ALL_MANAGERS_CAN_ADD",
  whoCanApproveMembers: "ALL_MANAGERS_CAN_APPROVE",
  whoCanApproveMessages: "OWNERS_AND_MANAGERS",
  whoCanAssignTopics: "OWNERS_AND_MANAGERS",
  whoCanAssistContent: "OWNERS_AND_MANAGERS",
  whoCanBanUsers: "OWNERS_AND_MANAGERS",
  whoCanContactOwner: "ANYONE_CAN_CONTACT",
  whoCanDeleteAnyPost: "OWNERS_AND_MANAGERS",
  whoCanDeleteTopics: "OWNERS_AND_MANAGERS",
  whoCanDiscoverGroup: "ALL_IN_DOMAIN_CAN_DISCOVER",
  whoCanEnterFreeFormTags: "OWNERS_AND_MANAGERS",
  whoCanHideAbuse: "OWNERS_AND_MANAGERS",
  whoCanInvite: "ALL_MANAGERS_CAN_INVITE",
  whoCanJoin: "INVITED_CAN_JOIN",
  whoCanLeaveGroup: "ALL_MEMBERS_CAN_LEAVE",
  whoCanLockTopics: "OWNERS_AND_MANAGERS",
  whoCanMakeTopicsSticky: "OWNERS_AND_MANAGERS",
  whoCanMarkDuplicate: "OWNERS_AND_MANAGERS",
  whoCanMarkFavoriteReplyOnAnyTopic: "OWNERS_AND_MANAGERS",
  whoCanMarkNoResponseNeeded: "OWNERS_AND_MANAGERS",
  whoCanModerateContent: "OWNERS_AND_MANAGERS",
  whoCanModerateMembers: "OWNERS_AND_MANAGERS",
  whoCanModifyMembers: "OWNERS_AND_MANAGERS",
  whoCanModifyTagsAndCategories: "OWNERS_AND_MANAGERS",
  whoCanMoveTopicsIn: "OWNERS_AND_MANAGERS",
  whoCanMoveTopicsOut: "OWNERS_AND_MANAGERS",
  whoCanPostAnnouncements: "OWNERS_AND_MANAGERS",
  whoCanPostMessage: "ALL_MANAGERS_CAN_POST",
  whoCanTakeTopics: "OWNERS_AND_MANAGERS",
  whoCanUnassignTopic: "OWNERS_AND_MANAGERS",
  whoCanUnmarkFavoriteReplyOnAnyTopic: "OWNERS_AND_MANAGERS",
  whoCanViewGroup: "ALL_MEMBERS_CAN_VIEW",
  whoCanViewMembership: "ALL_MEMBERS_CAN_VIEW",
};

const crew: GroupSettings = {
  allowExternalMembers: "true",
  allowWebPosting: "true",
  archiveOnly: "false",
  customFooterText: "",
  customRolesEnabledForSettingsToBeMerged: "false",
  defaultMessageDenyNotificationText: "",
  default_sender: "DEFAULT_SELF",
  enableCollaborativeInbox: "false",
  favoriteRepliesOnTop: "true",
  includeCustomFooter: "false",
  includeInGlobalAddressList: "true",
  isArchived: "true",
  maxMessageBytes: 26214400,
  membersCanPostAsTheGroup: "true",
  messageDisplayFont: "DEFAULT_FONT",
  messageModerationLevel: "MODERATE_NONE",
  primaryLanguage: "en_US",
  replyTo: "REPLY_TO_IGNORE",
  sendMessageDenyNotification: "false",
  showInGroupDirectory: "false",
  spamModerationLevel: "REJECT",
  whoCanAdd: "ALL_MANAGERS_CAN_ADD",
  whoCanAddReferences: "NONE",
  whoCanApproveMembers: "ALL_MANAGERS_CAN_APPROVE",
  whoCanApproveMessages: "OWNERS_AND_MANAGERS",
  whoCanAssignTopics: "ALL_MEMBERS",
  whoCanAssistContent: "ALL_MEMBERS",
  whoCanBanUsers: "OWNERS_AND_MANAGERS",
  whoCanContactOwner: "ANYONE_CAN_CONTACT",
  whoCanDeleteAnyPost: "OWNERS_AND_MANAGERS",
  whoCanDeleteTopics: "OWNERS_AND_MANAGERS",
  whoCanDiscoverGroup: "ALL_IN_DOMAIN_CAN_DISCOVER",
  whoCanEnterFreeFormTags: "ALL_MEMBERS",
  whoCanHideAbuse: "ALL_MEMBERS",
  whoCanInvite: "ALL_MANAGERS_CAN_INVITE",
  whoCanJoin: "INVITED_CAN_JOIN",
  whoCanLeaveGroup: "ALL_MEMBERS_CAN_LEAVE",
  whoCanLockTopics: "OWNERS_AND_MANAGERS",
  whoCanMakeTopicsSticky: "ALL_MEMBERS",
  whoCanMarkDuplicate: "ALL_MEMBERS",
  whoCanMarkFavoriteReplyOnAnyTopic: "ALL_MEMBERS",
  whoCanMarkFavoriteReplyOnOwnTopic: "ALL_MEMBERS",
  whoCanMarkNoResponseNeeded: "ALL_MEMBERS",
  whoCanModerateContent: "OWNERS_AND_MANAGERS",
  whoCanModerateMembers: "OWNERS_AND_MANAGERS",
  whoCanModifyMembers: "OWNERS_AND_MANAGERS",
  whoCanModifyTagsAndCategories: "ALL_MEMBERS",
  whoCanMoveTopicsIn: "OWNERS_AND_MANAGERS",
  whoCanMoveTopicsOut: "OWNERS_AND_MANAGERS",
  whoCanPostAnnouncements: "OWNERS_AND_MANAGERS",
  whoCanPostMessage: "ANYONE_CAN_POST",
  whoCanTakeTopics: "ALL_MEMBERS",
  whoCanUnassignTopic: "ALL_MEMBERS",
  whoCanUnmarkFavoriteReplyOnAnyTopic: "ALL_MEMBERS",
  whoCanViewGroup: "ALL_MEMBERS_CAN_VIEW",
  whoCanViewMembership: "ALL_MEMBERS_CAN_VIEW",
};

const inbox: GroupSettings = {
  allowExternalMembers: "true",
  allowGoogleCommunication: "false",
  allowWebPosting: "true",
  archiveOnly: "false",
  customFooterText: "",
  customRolesEnabledForSettingsToBeMerged: "false",
  defaultMessageDenyNotificationText: "",
  default_sender: "GROUP",
  enableCollaborativeInbox: "true",
  favoriteRepliesOnTop: "true",
  includeCustomFooter: "false",
  includeInGlobalAddressList: "true",
  isArchived: "true",
  maxMessageBytes: 26214400,
  membersCanPostAsTheGroup: "true",
  messageDisplayFont: "DEFAULT_FONT",
  messageModerationLevel: "MODERATE_NONE",
  primaryLanguage: "en_US",
  replyTo: "REPLY_TO_IGNORE",
  sendMessageDenyNotification: "false",
  showInGroupDirectory: "false",
  spamModerationLevel: "MODERATE",
  whoCanAdd: "ALL_MANAGERS_CAN_ADD",
  whoCanAddReferences: "NONE",
  whoCanApproveMembers: "ALL_MANAGERS_CAN_APPROVE",
  whoCanApproveMessages: "ALL_MEMBERS",
  whoCanAssignTopics: "OWNERS_AND_MANAGERS",
  whoCanAssistContent: "OWNERS_AND_MANAGERS",
  whoCanBanUsers: "OWNERS_AND_MANAGERS",
  whoCanContactOwner: "ANYONE_CAN_CONTACT",
  whoCanDeleteAnyPost: "ALL_MEMBERS",
  whoCanDeleteTopics: "ALL_MEMBERS",
  whoCanDiscoverGroup: "ALL_IN_DOMAIN_CAN_DISCOVER",
  whoCanEnterFreeFormTags: "OWNERS_AND_MANAGERS",
  whoCanHideAbuse: "OWNERS_AND_MANAGERS",
  whoCanInvite: "ALL_MANAGERS_CAN_INVITE",
  whoCanJoin: "INVITED_CAN_JOIN",
  whoCanLeaveGroup: "ALL_MEMBERS_CAN_LEAVE",
  whoCanLockTopics: "ALL_MEMBERS",
  whoCanMakeTopicsSticky: "OWNERS_AND_MANAGERS",
  whoCanMarkDuplicate: "OWNERS_AND_MANAGERS",
  whoCanMarkFavoriteReplyOnAnyTopic: "OWNERS_AND_MANAGERS",
  whoCanMarkFavoriteReplyOnOwnTopic: "OWNERS_AND_MANAGERS",
  whoCanMarkNoResponseNeeded: "OWNERS_AND_MANAGERS",
  whoCanModerateContent: "ALL_MEMBERS",
  whoCanModerateMembers: "OWNERS_AND_MANAGERS",
  whoCanModifyMembers: "OWNERS_AND_MANAGERS",
  whoCanModifyTagsAndCategories: "OWNERS_AND_MANAGERS",
  whoCanMoveTopicsIn: "ALL_MEMBERS",
  whoCanMoveTopicsOut: "ALL_MEMBERS",
  whoCanPostAnnouncements: "ALL_MEMBERS",
  whoCanPostMessage: "ANYONE_CAN_POST",
  whoCanTakeTopics: "OWNERS_AND_MANAGERS",
  whoCanUnassignTopic: "OWNERS_AND_MANAGERS",
  whoCanUnmarkFavoriteReplyOnAnyTopic: "OWNERS_AND_MANAGERS",
  whoCanViewGroup: "ALL_MEMBERS_CAN_VIEW",
  whoCanViewMembership: "ALL_MEMBERS_CAN_VIEW",
};

const participants: GroupSettings = {
  allowExternalMembers: "true",
  allowWebPosting: "true",
  archiveOnly: "false",
  customFooterText: "",
  customRolesEnabledForSettingsToBeMerged: "false",
  defaultMessageDenyNotificationText: "",
  default_sender: "DEFAULT_SELF",
  enableCollaborativeInbox: "false",
  includeCustomFooter: "false",
  includeInGlobalAddressList: "true",
  isArchived: "true",
  maxMessageBytes: 26214400,
  membersCanPostAsTheGroup: "false",
  messageModerationLevel: "MODERATE_NONE",
  replyTo: "REPLY_TO_IGNORE",
  sendMessageDenyNotification: "true",
  showInGroupDirectory: "false",
  spamModerationLevel: "MODERATE",
  whoCanAdd: "ALL_MANAGERS_CAN_ADD",
  whoCanApproveMembers: "ALL_MANAGERS_CAN_APPROVE",
  whoCanApproveMessages: "OWNERS_AND_MANAGERS",
  whoCanAssignTopics: "OWNERS_AND_MANAGERS",
  whoCanAssistContent: "OWNERS_AND_MANAGERS",
  whoCanBanUsers: "OWNERS_AND_MANAGERS",
  whoCanContactOwner: "ANYONE_CAN_CONTACT",
  whoCanDeleteAnyPost: "OWNERS_AND_MANAGERS",
  whoCanDeleteTopics: "OWNERS_AND_MANAGERS",
  whoCanDiscoverGroup: "ALL_IN_DOMAIN_CAN_DISCOVER",
  whoCanEnterFreeFormTags: "OWNERS_AND_MANAGERS",
  whoCanHideAbuse: "OWNERS_AND_MANAGERS",
  whoCanInvite: "ALL_MANAGERS_CAN_INVITE",
  whoCanJoin: "INVITED_CAN_JOIN",
  whoCanLeaveGroup: "ALL_MEMBERS_CAN_LEAVE",
  whoCanLockTopics: "OWNERS_AND_MANAGERS",
  whoCanMakeTopicsSticky: "OWNERS_AND_MANAGERS",
  whoCanMarkDuplicate: "OWNERS_AND_MANAGERS",
  whoCanMarkFavoriteReplyOnAnyTopic: "OWNERS_AND_MANAGERS",
  whoCanMarkNoResponseNeeded: "OWNERS_AND_MANAGERS",
  whoCanModerateContent: "OWNERS_AND_MANAGERS",
  whoCanModerateMembers: "OWNERS_AND_MANAGERS",
  whoCanModifyMembers: "OWNERS_AND_MANAGERS",
  whoCanModifyTagsAndCategories: "OWNERS_AND_MANAGERS",
  whoCanMoveTopicsIn: "OWNERS_AND_MANAGERS",
  whoCanMoveTopicsOut: "OWNERS_AND_MANAGERS",
  whoCanPostAnnouncements: "OWNERS_AND_MANAGERS",
  whoCanPostMessage: "ALL_MEMBERS_CAN_POST",
  whoCanTakeTopics: "OWNERS_AND_MANAGERS",
  whoCanUnassignTopic: "OWNERS_AND_MANAGERS",
  whoCanUnmarkFavoriteReplyOnAnyTopic: "OWNERS_AND_MANAGERS",
  whoCanViewGroup: "ALL_MEMBERS_CAN_VIEW",
  whoCanViewMembership: "ALL_MEMBERS_CAN_VIEW",
};

export const GROUP_SETTINGS_TEMPLATES = { announcement, crew, inbox, participants } as const satisfies Record<
  string,
  GroupSettings
>;

export type GroupSettingsTemplateName = keyof typeof GROUP_SETTINGS_TEMPLATES;

export const GROUP_SETTINGS_TEMPLATE_NAMES = Object.keys(GROUP_SETTINGS_TEMPLATES) as GroupSettingsTemplateName[];

/** Looks up a template by name, e.g. what `google_groups.settings_template` stores. Throws on an
 * unrecognized name rather than returning `null`, so a typo fails the settings pass for that group
 * instead of leaving it silently unmanaged. */
export function resolveGroupSettingsTemplate(name: string): GroupSettings {
  if (!Object.prototype.hasOwnProperty.call(GROUP_SETTINGS_TEMPLATES, name)) {
    throw new Error(
      `Unknown Google Group settings template "${name}"; expected one of ${GROUP_SETTINGS_TEMPLATE_NAMES.join(", ")}`,
    );
  }
  return GROUP_SETTINGS_TEMPLATES[name as GroupSettingsTemplateName];
}
