name: crm
description: The CRM app's Directus schema and permission rules.
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-typescript
