#!/usr/bin/env bash
# This command writes all groups to the GAM_SPREADSHEET_ID "Groups Export" sheet.
set -euxo pipefail

sheet_name="Groups Export"

gam print groups name description settings \
    todrive \
    tduser ${GAM_ADMIN_USER} \
    tdfileid "${GAM_SPREADSHEET_ID}" tdretaintitle \
    tdsheet "${sheet_name}" tdupdatesheet \
    tdnobrowser tdnoemail
